### 1) Test Authorization Endpoint (OpenId Connect login start - interactive)
GET https://localhost/connect/authorize?client_id=my-override-client-id&redirect_uri=https://localhost/signin-oidc&response_type=code&scope=openid%20profile%20email&state=12345&code_challenge=...&code_challenge_method=S256

###

### 2) Test Token Endpoint (exchange auth code or password for tokens)

# Example for Resource Owner Password Credentials Grant (testing only)
POST https://localhost/connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&username=user&password=Pass123$&client_id=my-override-client-id&scope=openid profile email

###

### 3) Test UserInfo Endpoint (requires valid access token)
GET https://localhost/connect/userinfo
Accept: application/json
Authorization: Bearer CfDJ8NF2-NNkK91BsAs8WnfU0DhwbGTxTZDTKOTmvbwMfzLCDQNZwvs4aUgHvwphTLul-jGTd_e5PwJNMXMxxa4jYCd7V6S0YYIuxf8sQ1g6VBB5VRZq5HWPXpY0BXLIZpaOky5iDZZcZakEAtsAlz8QQp9DZWVnv6rTZAcfgLs9MdQVrGdvxlCHPGt1HlVky2PMiVWtck1TjAJAncds-tdeZad3c5f7rT4xtz9EWfBowwGj_fBJuyPEs1Ku3mdoRS4txZ_Ufga2QdxSYz13Xr65I2fL1I9dP9cp6-Z6LEb4xuKJZy4rFAbBIRO2kF3QGDV-CDcVsrbJG0HaEX5kNH0cm3ZMt7VyWszlRsIE-j7gyXmqD9KcUwNT4XBluyhhv-EOczZa2vpO2KNIv99p4RvddjJydMKRKTyfRPI_SmCA2Yh6hSvKuuLi4VayIC6hvjjjime9D0Bcnav_mRjNHREf_qpwIUqH-7PkJ4KCHCeC1xp-fnulY4FwyxUUhPELprE-8iian9JTD3NWfRqL21a9uL52y1MJ-B_s2tMeG-ziql_DQ8V_MdXQ_kL6Py9CSnDGdMJ7Kkvi7D802DB36-5RR1dlmE9kyi0w2D_ziyZDwtPy2jswrfEQ9_d4gxSjVRhyHRB-iezyW4rUCXiNlogCW-xwhkbZflaau4aOagQdFhLy
###

### 4) Test Logout Endpoint

GET https://localhost:7056/connect/logout?id_token_hint=eyJhbGciOi...&post_logout_redirect_uri=https://localhost:7104/cs/signout-callback-oidc&state=xyz123

###